version: '3.8'

services:
  frontend:
    build:
      context: ./CarGal_front/CarGal
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./CarGal_back
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - NODE_ENV=production
    volumes:
      - online-data:/app/onlineData

volumes:
  online-data:
